services:
  - type: web
    name: peoplethenewappbetterthanthebluebotandwithoutcapitalism
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PEOPLE_MESSAGE_ENCRYPTION_KEY
        sync: false
      - key: NODE_ENV
        value: production
